version: '3.4'

services:
  basketdb:
    image: redis

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build: 
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile

  catalogdb:
    image: mongo

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile
   
  discountdb:
    image: postgres
  
  pgadmin:
    image: dpage/pgadmin4


volumes:
  portainer_data:
  postgres_data:  
  pgadmin_data:  